---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    author: jack
spec:
  replicas: 2
  selector:
    matchLabels:
      author: jack
  template:
    metadata:
      name: nginx-pod
      labels:
        author: jack
    spec:
      containers:
        - name: mynginx
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: slavename
                    operator: In
                    values:
                      - jack
...