---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: jack
spec:
  containers:
    - name: mynginx
      image: nginx
  tolerations:
    - key: node1
      operator: Equal
      value: hbc1
      effect: NoSchedule
...